#服务器配置
server:
  servlet:
    context-path: /annotation
  port: 9090

spring:
  profiles:
    active: rel
---

#数据源配置
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/annotation?characterEncoding=utf-8
    username: root
    password: 123456

#运行参数
props:
  basePath: F:/data/annotation
  clipHome: F:/data/annotation/clips
  originVideoHome: F:/data/annotation/video/origin
  undividedVideoHome:  F:/data/annotation/video/processed/undivided
  videoHome: F:/data/annotation/video/processed
  imageHome:  F:/data/annotation/image
  stepSize: 1
  serverAddress: 192.168.1.120:8080/annotation
  videoTypes: mp4,avi,mkv,flv,rmvb,wmv,m4v,asf,rm,3gp,mov

---
#数据源配置
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.250:3306/annotation?characterEncoding=utf-8
    username: root
    password: 123456

#运行参数
props:
  basePath: /usr/annotation
  clipHome: /usr/annotation/clips
  originVideoHome: /usr/annotation/video/origin
  undividedVideoHome:  /usr/annotation/video/processed/undivided
  videoHome: /usr/annotation/video/processed
  imageHome:  /usr/annotation/image
  stepSize: 1
  serverAddress: 192.168.1.250:18080/annotation
  videoTypes: mp4,avi,mkv,flv,rmvb,wmv,m4v,asf,rm,3gp,mov

---
#数据源配置
spring:
  profiles: rel
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.250:3306/annotation?characterEncoding=utf-8
    username: root
    password: 123456

  #运行参数
props:
  basePath: /usr/annotation
  clipHome: /usr/annotation/clips
  originVideoHome: /usr/annotation/video/origin
  undividedVideoHome:  /usr/annotation/video/processed/undivided
  videoHome: /usr/annotation/video/processed
  imageHome:  /usr/annotation/image
  stepSize: 1
  serverAddress: tiansilab.dynamic-dns.net:18080/annotation
  videoTypes: mp4,avi,mkv,flv,rmvb,wmv,m4v,asf,rm,3gp,mov

